#pragma once
#include <vector>
#include <windows.h>
#include <tlhelp32.h>
#include <iostream>
#include <evntrace.h> 
#include <evntcons.h>  
#include <initguid.h> 
#include <guiddef.h>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <ctime>
#include <tdh.h>
#include <thread>
#include <atomic>
